name: Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  audit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit

  check:
    runs-on: ubuntu-latest
    needs: [fmt, clippy, audit]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose

  build:
    runs-on: ubuntu-latest
    needs: [fmt, clippy, audit]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [fmt, clippy, audit]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
