name: Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  check:
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose


  test:
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    if: always()
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ vars.SQLX_VERSION }}
          --features ${{ vars.SQLX_FEATURES }}
          --no-default-features
          --locked

      - name: Migrate database
        run: SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Run tests
        run: cargo test --verbose
